#!/usr/bin/env bash
# Mixes the subtle music bed under the voiceover of all three videos with
# sidechain ducking (music dips while narration is speaking).
#
# Prereqs: ffmpeg on PATH, assets/music-bed.wav generated by
# scripts/make_music_bed.py, and out/{launch,short-15s,short-30s}.mp4 rendered
# by remotion (voiceover already burned in).
#
#   bash scripts/mix_music.sh
set -euo pipefail
cd "$(dirname "$0")/.."

BED=assets/music-bed.wav
# 16s loop at 44.1kHz = 705600 samples/channel
SIZE=705600
# sidechain settings: bed dips ~10-15dB while the voice is speaking
SC="sidechaincompress=threshold=0.012:ratio=6:attack=20:release=600:makeup=1"
OUTCHAIN="amix=inputs=2:duration=first:dropout_transition=0:normalize=0,alimiter=limit=0.95"

mix() { # $1=video  $2=fade-in  $3=fade-out start  $4=fade-out dur
  local v=$1 f_in=$2 f_out_s=$3 f_out_d=$4 tmp
  tmp="/tmp/mix-${v}.mp4"
  ffmpeg -y -v error -i "out/${v}.mp4" -i "$BED" -filter_complex \
    "[1:a]aloop=loop=-1:size=${SIZE},volume=0.55,afade=t=in:st=0:d=${f_in},afade=t=out:st=${f_out_s}:d=${f_out_d}[bg];\
     [bg][0:a]${SC}[duck];\
     [0:a][duck]${OUTCHAIN}[aout]" \
    -map 0:v -map "[aout]" -c:v copy -c:a aac -b:a 192k "$tmp"
  mv "$tmp" "out/${v}.mp4"
  echo "mixed ${v}.mp4"
}

mix launch 2 112 8
mix short-30s 1 27 3
mix short-15s 1 12.5 2.5
echo "done — all three videos have music bed + ducking"
