name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can reproduce and fix it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: "When I call /v1/transactions/transfer-sol, the API returns a 500 error instead of..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: "The transaction should have been submitted and returned a signature."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Create an agent via POST /v1/agents
        2. Fund the wallet with devnet SOL
        3. Call POST /v1/transactions/transfer-sol with amount_sol=0.1
        4. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AgentWallet is affected?
      options:
        - API (Backend)
        - Python SDK
        - MCP Server
        - Dashboard (Frontend)
        - Solana Program (On-chain)
        - CLI
        - Docker / Deployment
        - Documentation
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error output
      description: Paste any relevant logs or error messages.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details.
      value: |
        - OS:
        - Python version:
        - SDK version:
        - Docker: yes/no
        - Network: devnet / mainnet
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version
          required: false
