name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make AgentWallet better? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why is it needed?
      placeholder: "AI agents currently can't do X because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Be as specific as you can.
      placeholder: |
        Add a new endpoint POST /v1/agents/{id}/subscribe that allows...

        SDK usage:
        ```python
        await aw.agents.subscribe(agent_id, events=["transfer", "escrow"])
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AgentWallet would this affect?
      multiple: true
      options:
        - API (Backend)
        - Python SDK
        - MCP Server
        - Dashboard (Frontend)
        - Solana Program (On-chain)
        - CLI
        - Documentation
        - New component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Important — affects my workflow
        - Critical — blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
