name: Security Vulnerability
description: Report a security issue (non-critical). For critical vulnerabilities, email web3youth@gmail.com directly.
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **For critical vulnerabilities (key exposure, fund theft, auth bypass), please email web3youth@gmail.com directly. Do NOT open a public issue.**

        Use this template only for non-critical security concerns.

  - type: textarea
    id: description
    attributes:
      label: Security concern
      description: Describe the security issue.
      placeholder: "The rate limiter can be bypassed by..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low — minor concern, no immediate risk
        - Medium — potential risk under specific conditions
        - High — email web3youth@gmail.com instead
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected component
      options:
        - Authentication / Authorization
        - Key Management / Encryption
        - Transaction Processing
        - Escrow System
        - Solana Program (On-chain)
        - API Input Validation
        - Rate Limiting
        - Webhooks
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential impact
      description: What could happen if this is exploited?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we verify this issue?
    validations:
      required: false
